#!/bin/bash
# Aitor Maraña Pérez
# Fecha 24/02/2026
if [ $USER != "root" ];then
	echo "Error: Usted no es usuario root"
	exit 1
fi
case $# in

	3)
		for ((b=1; b<=10; b++))
		do
			usuario="${1}${b}"
			pwd=$(openssl passwd -6 $2)
			group=$3
			if id $usuario &>/dev/null; then
				echo "error el usuario ya existe"
			fi
		
			if ! getent group "$3" > /dev/null; then
				echo "El grupo de usuarios no existe, sera creado"
				addgroup $3
			fi
			echo "creando usuario: $usuarios"
			useradd -m -g "usuarios" -p "$pwd" $usuario
		done
	;;
	
	4)
	        for ((b=1; b<=$4; b++))
                do
                        usuario="${1}${b}"
                	pwd=$(openssl passwd -6 $2)
			group=$3
			if id $usuario &>/dev/null; then
                                echo "error el usuario ya existe"
                        fi

                        if ! getent group "$3" > /dev/null; then
                                echo "El grupo usuarios no existe, sera creado"
                                addgroup "$3"
			fi
		        echo "creando usuario: $usuario"
			useradd -m -g "usuarios" -p "$pwd" $usuario
                done
	;;

	*)
		echo "Error: Numero de parametros equivocado"
		exit 1
	;;
esac
